dist: xenial
sudo: false
language: python

if: type = pull_request OR type = push
  python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

  stages:
    - lint
    - test

  jobs:
    include:
      - stage: lint
        python: "3.7"
        env: TOXENV=lint

if: type = cron
  python: "3.7"
  env: TOXENV=py37


install: pip install tox-travis
script: tox
