dist: xenial
sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python: "3.7"
      env: TOXENV=lint

install: pip install tox-travis
script: tox
