dist: xenial
sudo: false
language: python

branches:
  only:
  - master
  - develop


stages:
- name: lint
  if: type != cron
- name: test
  if: type != cron

jobs:
  include:
  - stage: lint
    python: "3.7"
    env: TOXENV=lint

  - stage: test
    python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    if: type != cron

  - name: periodic
    python: "3.7"
    env: TOXENV=py37
    if: type = cron

install: pip install tox-travis
script: tox
