[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
dist-name = "rofi-tmuxp"
module = "rofi_tmuxp"
author = "Heinrich Kruger"
author-email = "heindsight@kruger.dev"
home-page = "https://github.com/heindsight/rofi-tmuxp"
description-file = "README.rst"
keywords = "rofi tmux tmuxp"
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Topic :: Desktop Environment :: Window Managers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
requires-python = "~=3.5"
requires = [
    "kaptan ~= 0.5.9",
    "tmuxp ~= 1.1"
]

[tool.flit.metadata.requires-extra]
dev = [
    "pdbpp",
]
test = [
    "black; python_version >= '3.6'",
    "flake8",
    "isort ~= 5.0.0",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-randomly",
    "rstcheck",
]

[tool.flit.scripts]
rofi-tmuxp = "rofi_tmuxp:main"

[tool.isort]
profile="black"
lines_after_imports = 2
