[tool.poetry]
name = "rofi-tmuxp"
version = "0.0.1"
description = "Rofi script to launch tmuxp sessions"
authors = ["Heinrich Kruger <heindsight@kruger.dev>"]
readme = "README.rst"
license = "MIT"
keywords = ["rofi", "tmux", "tmuxp"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: End Users/Desktop",
]
packages = [
    {include = "rofi_tmuxp.py", from="src"},
]
include = [
    "LICENSE",
    "README.rst",
]

[tool.poetry.dependencies]
python = "^3.6"
kaptan = "^0.5.12"
tmuxp = "^1.5"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
coverage = "^4.5"
flake8 = "^3.7"
isort = "^4.3"
pdbpp = "^0.10.0"
pytest = "^5.1"
tox = "^3.14"

[tool.poetry.scripts]
rofi-tmux = "rofi_tmuxp:main"

[tool.isort]
line_width = 88
multi_line_output = 5
lines_after_imports = 2
known_first_party = ["test"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
