[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
dist-name = "rofi-tmuxp"
module = "rofi_tmuxp"
author = "Heinrich Kruger"
author-email = "heindsight@kruger.dev"
home-page = "https://github.com/heindsight/rofi-tmuxp"
description-file = "README.rst"
keywords = "rofi tmux tmuxp"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Topic :: Desktop Environment :: Window Managers"
]
requires-python = "~=3.5"
requires = [
    "kaptan ~= 0.5.7",
    "tmuxp ~= 1.1"
]

[tool.flit.metadata.requires-extra]
dev = [
    "pdbpp",
]
test = [
    "black; python_version >= '3.6'",
    "flake8",
    "isort",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "rstcheck",
]

[tool.flit.scripts]
rofi-tmux = "rofi_tmuxp:main"

[tool.isort]
line_width = 88
multi_line_output = 5
lines_after_imports = 2
known_first_party = ["test"]
