---
name: Build and publish package

on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit
      - name: Build package
        run: flit build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-packages
          path: dist/

  publish-test-pypi:
    if: github.action == 'published' && github.event.release.draft
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-packages
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  publish-pypi:
    if: github.action == 'published' && ! github.event.release.draft
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-packages
      - name: publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
